<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: samy
 * Date: Tue, 04 Jul 2017 18:16:49 +0200
 */

$conf['title'] = 'Wiki Summer Camp 2017';
$conf['lang'] = 'fr';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
